-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-20 18:37:44 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE
--drop table programari;
--drop table CLIENT;
--drop table antrenor;
--drop table tip_antrenament;
--drop table tip_client;
--drop table reduceri;

CREATE TABLE antrenor (
    id_antrenor             NUMBER(3) NOT NULL,
    name_antrenor           VARCHAR2(25 CHAR) NOT NULL,
    tip_antrenament_id_type NUMBER(3) NOT NULL,
    start_program           DATE NOT NULL,
    end_program             DATE NOT NULL
);

ALTER TABLE antrenor ADD CONSTRAINT antrenor_pk PRIMARY KEY ( id_antrenor );

CREATE TABLE client (
    id_client               NUMBER(3) NOT NULL,
    name_client             VARCHAR2(20 CHAR) NOT NULL,
    telefon                 NUMBER(10) NOT NULL,
    tip_client_id_tclient   NUMBER(2) NOT NULL,
    tip_antrenament_id_type NUMBER(3) NOT NULL,
    start_time              DATE NOT NULL,
    end_time                DATE NOT NULL
);

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE programari (
    id_programare        NUMBER(5) NOT NULL,
    client_id_client     NUMBER(3) NOT NULL,
    antrenor_id_antrenor NUMBER(3) NOT NULL,
    programare_start     DATE NOT NULL,
    programare_end       DATE NOT NULL
);

ALTER TABLE programari ADD CONSTRAINT programari_pk PRIMARY KEY ( id_programare );

ALTER TABLE programari
    ADD CONSTRAINT programari__un UNIQUE ( programare_start,
                                           antrenor_id_antrenor,
                                           programare_end );

CREATE TABLE reduceri (
    id_reducere NUMBER(1) NOT NULL,
    reducere    NUMBER(2, 2) NOT NULL,
    observatii  VARCHAR2(100)
);

ALTER TABLE reduceri ADD CONSTRAINT reduceri_pk PRIMARY KEY ( id_reducere );

CREATE TABLE tip_antrenament (
    id_type          NUMBER(3) NOT NULL,
    name_antrenament VARCHAR2(25) NOT NULL,
    cost_abonament   NUMBER
);

ALTER TABLE tip_antrenament ADD CONSTRAINT tip_antrenament_pk PRIMARY KEY ( id_type );

CREATE TABLE tip_client (
    id_tclient           NUMBER(2) NOT NULL,
    name_tclient         VARCHAR2(25 CHAR) NOT NULL,
    reduceri_id_reducere NUMBER(2) NOT NULL
);

CREATE UNIQUE INDEX tip_client__idxv1 ON
    tip_client (
        reduceri_id_reducere
    ASC );

ALTER TABLE tip_client ADD CONSTRAINT tip_client_pk PRIMARY KEY ( id_tclient );

ALTER TABLE antrenor
    ADD CONSTRAINT antrenor_tip_antrenament_fk FOREIGN KEY ( tip_antrenament_id_type )
        REFERENCES tip_antrenament ( id_type );

ALTER TABLE client
    ADD CONSTRAINT client_tip_antrenament_fk FOREIGN KEY ( tip_antrenament_id_type )
        REFERENCES tip_antrenament ( id_type );

ALTER TABLE client
    ADD CONSTRAINT client_tip_client_fk FOREIGN KEY ( tip_client_id_tclient )
        REFERENCES tip_client ( id_tclient );

ALTER TABLE programari
    ADD CONSTRAINT programari_antrenor_fk FOREIGN KEY ( antrenor_id_antrenor )
        REFERENCES antrenor ( id_antrenor );

ALTER TABLE programari
    ADD CONSTRAINT programari_client_fk FOREIGN KEY ( client_id_client )
        REFERENCES client ( id_client );

ALTER TABLE tip_client
    ADD CONSTRAINT tip_client_reduceri_fk FOREIGN KEY ( reduceri_id_reducere )
        REFERENCES reduceri ( id_reducere );

CREATE SEQUENCE antrenor_id_antrenor_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER antrenor_id_antrenor_trg BEFORE
    INSERT ON antrenor
    FOR EACH ROW
    WHEN ( new.id_antrenor IS NULL )
BEGIN
    :new.id_antrenor := antrenor_id_antrenor_seq.nextval;
END;
/

CREATE SEQUENCE client_id_client_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER client_id_client_trg BEFORE
    INSERT ON client
    FOR EACH ROW
    WHEN ( new.id_client IS NULL )
BEGIN
    :new.id_client := client_id_client_seq.nextval;
END;
/

CREATE SEQUENCE programari_id_programare_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER programari_id_programare_trg BEFORE
    INSERT ON programari
    FOR EACH ROW
    WHEN ( new.id_programare IS NULL )
BEGIN
    :new.id_programare := programari_id_programare_seq.nextval;
END;
/

CREATE SEQUENCE reduceri_id_reducere_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER reduceri_id_reducere_trg BEFORE
    INSERT ON reduceri
    FOR EACH ROW
    WHEN ( new.id_reducere IS NULL )
BEGIN
    :new.id_reducere := reduceri_id_reducere_seq.nextval;
END;
/

CREATE SEQUENCE tip_antrenament_id_type_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER tip_antrenament_id_type_trg BEFORE
    INSERT ON tip_antrenament
    FOR EACH ROW
    WHEN ( new.id_type IS NULL )
BEGIN
    :new.id_type := tip_antrenament_id_type_seq.nextval;
END;
/

CREATE SEQUENCE tip_client_id_tclient_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER tip_client_id_tclient_trg BEFORE
    INSERT ON tip_client
    FOR EACH ROW
    WHEN ( new.id_tclient IS NULL )
BEGIN
    :new.id_tclient := tip_client_id_tclient_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             13
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0