
drop table programari;
drop table CLIENT;
drop table antrenor;
drop table tip_antrenament;
drop table tip_client;
drop table reduceri;

-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-12-16 15:59:46 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE antrenor (
    id_antrenor   NUMBER(3) NOT NULL,
    name_antrenor VARCHAR2(25 CHAR) NOT NULL,
    start_program DATE NOT NULL,
    end_program   DATE NOT NULL
)
LOGGING;

ALTER TABLE antrenor
    ADD CONSTRAINT nume_antrenor_ck CHECK ( length(name_antrenor) >= 2
                                            AND REGEXP_LIKE ( name_antrenor,
                                                              '[A-Z]{1}[A-Za-z-]+ [A-Z]{1}[A-Za-z-]+$' ) );

ALTER TABLE antrenor ADD CONSTRAINT antrenor_program_ck CHECK ( start_program < end_program );

ALTER TABLE antrenor ADD CONSTRAINT antrenor_pk PRIMARY KEY ( id_antrenor );

CREATE TABLE client (
    id_client   NUMBER(3) NOT NULL,
    name_client VARCHAR2(20 CHAR) NOT NULL,
    start_time  DATE NOT NULL,
    end_time    DATE NOT NULL,
    id_type     NUMBER(3) NOT NULL,
    id_tclient  NUMBER(2) NOT NULL,
    telefon     NUMBER(10) NOT NULL
)
LOGGING;

ALTER TABLE client
    ADD CONSTRAINT nume_client_ck CHECK ( ( length(name_client) >= 2
                                            AND REGEXP_LIKE ( name_client,
                                                              '[A-Z]{1}[A-Za-z-]+ [A-Z]{1}[A-Za-z-]+$' ) ) );

ALTER TABLE client ADD CONSTRAINT "client_start<end_ck" CHECK ( start_time < end_time );

ALTER TABLE client
    ADD CONSTRAINT client_telefon_ck CHECK ( telefon BETWEEN 0720000000 AND 07699999999 );

ALTER TABLE client ADD CONSTRAINT client_pk PRIMARY KEY ( id_client );

CREATE TABLE programari (
    id_programare    NUMBER(5) NOT NULL,
    programare_start DATE NOT NULL,
    id_antrenor      NUMBER(3) NOT NULL,
    id_client        NUMBER(3) NOT NULL,
    programare_end   DATE NOT NULL
)
LOGGING;

ALTER TABLE programari ADD CONSTRAINT "programari_start<end_ck" CHECK ( programare_start < programare_end );

ALTER TABLE programari
    ADD CONSTRAINT programari_un UNIQUE ( id_antrenor,
                                          programare_start,
                                          programare_end );

CREATE TABLE reduceri (
    id_reducere NUMBER(2) NOT NULL,
    reducere    NUMBER(2, 2) NOT NULL,
    observatii  VARCHAR2(100)
)
LOGGING;

ALTER TABLE reduceri
    ADD CONSTRAINT reducere_ck CHECK ( reducere IN ( 0.1, 0.2, 0.3, 0 ) );

ALTER TABLE reduceri ADD CONSTRAINT reduceri_pk PRIMARY KEY ( id_reducere );

CREATE TABLE tip_antrenament (
    id_type          NUMBER(3) NOT NULL,
    name_antrenament VARCHAR2(25) NOT NULL,
    cost_abonament   NUMBER
)
LOGGING;

ALTER TABLE tip_antrenament
    ADD CONSTRAINT tip_antrenament_ck CHECK ( name_antrenament IN ( 'Fitness', 'Cardio', 'Crossfit', 'Pilates' ) );

ALTER TABLE tip_antrenament ADD CONSTRAINT cost_ck CHECK ( cost_abonament > 100 );

ALTER TABLE tip_antrenament ADD CONSTRAINT tip_antrenament_pk PRIMARY KEY ( id_type );

CREATE TABLE tip_client (
    id_tclient   NUMBER(2) NOT NULL,
    name_tclient VARCHAR2(25 CHAR) NOT NULL,
    id_reducere  NUMBER(2) NOT NULL
)
LOGGING;

ALTER TABLE tip_client
    ADD CONSTRAINT tip_client_ck CHECK ( name_tclient IN ( 'Student', 'Minor', 'Pensionar', 'Adult' ) );

CREATE UNIQUE INDEX tip_client__idx ON
    tip_client (
        id_reducere
    ASC )
        LOGGING;

ALTER TABLE tip_client ADD CONSTRAINT tip_client_pk PRIMARY KEY ( id_tclient );

ALTER TABLE client
    ADD CONSTRAINT client_tip_antrenament_fk FOREIGN KEY ( id_type )
        REFERENCES tip_antrenament ( id_type )
    NOT DEFERRABLE;

ALTER TABLE client
    ADD CONSTRAINT client_tip_client_fk FOREIGN KEY ( id_tclient )
        REFERENCES tip_client ( id_tclient )
    NOT DEFERRABLE;

ALTER TABLE programari
    ADD CONSTRAINT programari_antrenor_fk FOREIGN KEY ( id_antrenor )
        REFERENCES antrenor ( id_antrenor )
    NOT DEFERRABLE;

ALTER TABLE programari
    ADD CONSTRAINT programari_client_fk FOREIGN KEY ( id_client )
        REFERENCES client ( id_client )
    NOT DEFERRABLE;

ALTER TABLE tip_client
    ADD CONSTRAINT tip_client_reduceri_fk FOREIGN KEY ( id_reducere )
        REFERENCES reduceri ( id_reducere )
    NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER trg_programari_briu 
    BEFORE INSERT OR UPDATE ON PROGRAMARI 
    FOR EACH ROW 
BEGIN
	IF( :new.programare_start <= SYSDATE )
	THEN
		RAISE_APPLICATION_ERROR( -20001,
			'Data invalida: ' || TO_CHAR( :new.programare_start, 'DD.MM.YYYY HH24:MI:SS' ) || ' trebuie sa fie mai mare decat data curenta.' );
	END IF;
END; 
/

CREATE SEQUENCE antrenor_id_antrenor_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER antrenor_id_antrenor_trg BEFORE
    INSERT ON antrenor
    FOR EACH ROW
    WHEN ( new.id_antrenor IS NULL )
BEGIN
    :new.id_antrenor := antrenor_id_antrenor_seq.nextval;
END;
/

CREATE SEQUENCE programari_id_programare_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER programari_id_programare_trg BEFORE
    INSERT ON programari
    FOR EACH ROW
    WHEN ( new.id_programare IS NULL )
BEGIN
    :new.id_programare := programari_id_programare_seq.nextval;
END;
/

CREATE SEQUENCE reduceri_id_reducere_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER reduceri_id_reducere_trg BEFORE
    INSERT ON reduceri
    FOR EACH ROW
    WHEN ( new.id_reducere IS NULL )
BEGIN
    :new.id_reducere := reduceri_id_reducere_seq.nextval;
END;
/

CREATE SEQUENCE tip_antrenament_id_type_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER tip_antrenament_id_type_trg BEFORE
    INSERT ON tip_antrenament
    FOR EACH ROW
    WHEN ( new.id_type IS NULL )
BEGIN
    :new.id_type := tip_antrenament_id_type_seq.nextval;
END;
/

CREATE SEQUENCE tip_client_id_tclient_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER tip_client_id_tclient_trg BEFORE
    INSERT ON tip_client
    FOR EACH ROW
    WHEN ( new.id_tclient IS NULL )
BEGIN
    :new.id_tclient := tip_client_id_tclient_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             6
-- CREATE INDEX                             1
-- ALTER TABLE                             21
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          5
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
